version: '3.9'

services:
  api:
    build: .
    container_name: habit_tracker_api
    ports:
      - "5250:5250"   # HTTP
      - "7175:7175"   # HTTPS (if you configure it)
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=habit_tracker_db;Username=postgres;Password=postgres
      - ASPNETCORE_URLS=http://+:5250
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: docker.arvancloud.ir/postgres:16
    container_name: habit_tracker_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: habit_tracker_db
    ports:
      - "5432:5432"
    volumes:
      - habit_tracker_data:/var/lib/postgresql/data

volumes:
  habit_tracker_data:
